#!/usr/bin/env bash

set -CEeuo pipefail
IFS=$'\n\t'
shopt -s extdebug

resolve_link() {
  $(type -p greadlink readlink | head -1) "$1"
}

abs_dirname() {
  local cwd
  cwd="$(pwd)"
  local path="$1"

  while [ -n "$path" ]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$(resolve_link "$name" || true)"
  done

  pwd
  cd "$cwd"
}

get_dirname() {
  dirname "$(cd "$(dirname "$1")" && pwd)"
}

libexec_path="$(abs_dirname "$0")"
_DOTFILES_ROOT="$(abs_dirname "$libexec_path")"
export _DOTFILES_ROOT
export DOTFILES_DIR="$_DOTFILES_ROOT"

load_commonsh() {
  # shellcheck disable=SC1090
  source "$DOTFILES_DIR/libexec/lib/common.sh"
}

export -f load_commonsh

load_commonsh

export PATH="${libexec_path}:$PATH"

# Run locally
WORKSPACE_DIR="$(get_dirname "$DOTFILES_DIR/..")"
export WORKSPACE_DIR

command="${1:-""}"
case "$command" in
  "" | "-h" | "--help")
    exec dotfiles-help
    ;;
  *)
    command_path="$(command -v "dotfiles-$command" || true)"
    if [ ! -x "$command_path" ]; then
      echo "dotfiles: no such command \`$command'" >&2
      exit 1
    fi

    shift
    exec "$command_path" "$@"
    ;;
esac
