#!/usr/bin/env bash

set -CEeuo pipefail
IFS=$'\n\t'
shopt -s extdebug

load_commonsh

main() {
  header "Formatting $INDEX_JSON_PATH"
  cat $INDEX_JSON_PATH | jq . > tmp.json
  cp tmp.json $INDEX_JSON_PATH
  rm tmp.json
  header "Done!"
}

main "$@"
