#!/usr/bin/env bash

set -CEeuo pipefail
IFS=$'\n\t'
shopt -s extdebug

load_commonsh

main() {
  header "Putting files on system into repo"
  local FILE_NAME
  local SYSTEM_PATH
  local REPO_PATH
  let FINAL_INDEX=$FILES_COUNT-1
  for i in $(seq 0 $FINAL_INDEX); do
    if [[ $(there_is_system_configuration_for_index $i) == 'true' ]]; then
      FILE_NAME=$(file_name_for_index $i)
      SYSTEM_PATH=$(system_path_for_index $i)
      REPO_PATH=$(repo_path_for_index $i)
      cp -rT $SYSTEM_PATH $REPO_PATH
    fi
  done
  header "Done! Now just add and commit via git"
}

main "$@"
